### ISSUE TITLE
Add accepting branch name support for submodules

### ISSUE THREAD

**Issue by mohitsinhchavda** [junhoyeo/vercel-submodules#14]
Sometimes, the projects have to user submodule for a particular branch and not with the commmitHash, because everytime we merge the submodule PR
1. There might not be a change in main repo's codebase, so you might not want to do a commit just for the sake of adding latest commit hash of refference in main repo
2. it generates a new commit ID (of merge commit). So, for fast development and bigger teams, we have to make sure manually,that the build triggered for the main repo, was with the latest commit hash or not. 

Hence, having an option to give branch name, will make sure that the build is generated with sync of a particular branch only.

**Comment by junhoyeo** [comment]
I just felt the same need! Will work on it today.

**Comment by mohitsinhchavda** [comment]
hey @junhoyeo 
I also want to work on it, do you mind, if you let me pick this up?

i need help to understand, how to run it in local env before commiting, i am almost half way there

**Comment by junhoyeo** [comment]
> hey @junhoyeo I also want to work on it, do you mid, if you let me pick this up?
> 
> i need help to understand, how to run it in local env before commiting, i am almost half way there

@mohitsinhchavda Sure! Actually, I just pushed some work in #15, but I haven't tested it yet. Maybe you can start there! (You can open a new PR with your branch based from it (or some other implementation) and I'll close mine)

**Comment by junhoyeo** [comment]
bump!

**Comment by junhoyeo** [comment]
Confirmed that #15 works.

**Comment by junhoyeo** [comment]
@mohitsinhchavda Published in [v1.0.9](https://github.com/junhoyeo/vercel-submodules/releases/tag/v1.0.9)!
