### ISSUE TITLE
Build getting failed after the latest version release

### ISSUE THREAD

**Issue by dikshantrajput** [junhoyeo/vercel-submodules#17]
I had install the package in my project day before yesterday using this command 
`npm i -D vercel-submodules && npx vercel-submodules --all && npm install` and everything worked fine but after the latest update the same workflow seems to be broken and build is getting failed with just a message that 
<img width="829" alt="image" src="https://user-images.githubusercontent.com/57234452/222970832-1ce745a5-1c45-47eb-b3e2-949a0340c067.png">

**Comment by dikshantrajput** [comment]
I switched backed to version [1.0.8](https://www.npmjs.com/package/vercel-submodules/v/1.0.8) and everything worked fine. What is the issue in 1.0.9

**Comment by junhoyeo** [comment]
@dikshantrajput oh my, I'll make sure to check this issue right now.

**Comment by junhoyeo** [comment]
@dikshantrajput Just released a fix in [1.0.10](https://www.npmjs.com/package/vercel-submodules/v/1.0.10)!
