### ISSUE TITLE
Getting not our ref error

### ISSUE THREAD

**Issue by dikshantrajput** [junhoyeo/vercel-submodules#21]
Error! fatal: remote error: upload-pack: not our ref 360580bfd5f75d775b4e14552c0d442882f652d0
    at file:///vercel/path0/project/node_modules/vercel-submodules/lib/commands/clone.js:36:24
    exit code: 128 (Invalid exit argument)
Error: Command "npm i -D vercel-submodules@1.0.8 && npx vercel-submodules --all && npm install" exited with 1
BUILD_FAILED: Command "npm i -D vercel-submodules@1.0.8 && npx vercel-submodules --all && npm install" exited with 1

<img width="761" alt="image" src="https://user-images.githubusercontent.com/57234452/224324936-6231bac2-8695-4f2a-b01a-9514ad793344.png">

**Comment by dikshantrajput** [comment]
@junhoyeo Any progress on this?

**Comment by dikshantrajput** [comment]
@junhoyeo Issue solved. The issue was with the wrong checkout of my submodule. sorry for bothering you

**Comment by junhoyeo** [comment]
> @junhoyeo Issue solved. The issue was with the wrong checkout of my submodule. sorry for bothering you

Not at all! We should think of a way to catch & handle those cases.
