### ISSUE TITLE
Docs: additional steps for private submodules

### ISSUE THREAD

**Issue by achrafash** [junhoyeo/vercel-submodules#9]
Thank you @junhoyeo for this awesome tool! 🙏 

It just took me a while before understanding that in order to work (at least with private submodules) one has to:
1. [generate an access token](https://github.com/settings/tokens),
2. add it as an environment variable in Vercel (`GITHUB_TOKEN`).

I can open a PR to add the steps above in the README if you want.

**Comment by junhoyeo** [comment]
@AchrafAsh Of course, you are welcome to create a PR with a detailed exploration. It would sure be helpful for newbies!
